var valores ={
    si : [10,10,10,10],
    no : [0.01,0.01,0.01,0.01],
    nada : [0.01,0.01,1.2,2.2],
    poco : [1.2,2.2,3.4,4.4],
    regular : [3.4,4.4,5.6,6.6],
    mucho : [5.6,6.6,7.8,8.8],
    todo: [7.8 , 8.8, 10 , 10]
};

var dimensiones = {
    plausibilidad: [0,4],
    justificacion : [5,11],
    adecuacion : [12,26],
    exito : [24,49]
};

var P = [10,7,8,10,9,8,7,6,10,10,10,8,7,10,-2,5,7,8,8,8,6,3,8,3,3,-10,-6,7,8,-5,-9,8,7,4,4,8,5,6,-7,4,8,5,8,-6,7,-2,4,-6,8,5];
var PFinal = [8,3,8,5];

var tablaEj = [
'si',
'mucho',
'mucho',  
  9,
      9,
    'mucho',
    8,
    'mucho',
    'poco',
    'todo',
    'regular',
    'si',
    'mucho',
    'mucho',
    'regular',
    'regular',
    'regular',
    'si',
    'mucho',
    'poco',
    'mucho',
    'no',
    'si',
    'poco',
    'mucho',
    'no',
    'nada',
     'todo',
        'si',
        'no',
        'poco',
        'mucho',
        'regular',
        'mucho',
        'todo',
        'mucho',
        'regular',
        'mucho',
        'regular',
        'mucho',
        'mucho',
        'mucho',
        'si',
        'regular',
        'mucho',
            'mucho',
        'todo',
        'no',
        'mucho',
        'si'
];

/*[
'si',
'mucho',
'mucho',  
  10,
      9,
    'mucho',
    8,
    'mucho',
    'poco',
    'todo',
    'regular',
    'si',
    'mucho',
    'mucho',
    'regular',
    'regular',
    'regular',
    'si',
    'mucho',
    'poco',
    'mucho',
    'no',
    'si',
    'poco',
    'mucho',
    'no',
    'nada',
     'todo',
        'si',
        'no',
        'poco',
        'mucho',
        'regular',
        'mucho',
        'todo',
        'mucho',
        'mucho',
        'mucho',
        'poco',
        'mucho',
        'mucho',
        'mucho',
        'si',
        'regular',
        'mucho',
            'mucho',
        'todo',
        'no',
        'mucho',
        'si'
];*/
